# Generated by Django 2.0.3 on 2018-03-31 23:07

import ResourceCentre.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('beavers', models.BooleanField(default=False)),
                ('cubs', models.BooleanField(default=False)),
                ('scouts', models.BooleanField(default=True)),
                ('explorers', models.BooleanField(default=False)),
                ('network', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('curated', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False, help_text='Finished resource.')),
                ('leaders', models.IntegerField(default=3, help_text='Number of leaders needed.')),
                ('young_leaders', models.IntegerField(default=0, help_text='Number of young leaders.')),
                ('location', models.CharField(help_text='Event location.', max_length=256)),
                ('young_people_low', models.IntegerField(help_text='Minimum number of young people.')),
                ('young_people_high', models.IntegerField(help_text='Maximum number of young people.')),
                ('activity_size', models.CharField(choices=[('ID', 'Individual'), ('PA', 'Patrol'), ('TR', 'Troop'), ('DI', 'District'), ('CO', 'County'), ('NA', 'National'), ('IN', 'International')], default='TR', help_text='Activity size.', max_length=2)),
                ('inside_outside', models.CharField(choices=[('OU', 'Outside only'), ('IN', 'Inside only'), ('EI', 'Inside or outside'), ('BO', 'Inside and outside')], default='OU', help_text='Is the event inside, outside or both.', max_length=2)),
                ('contributors', models.ManyToManyField(blank=True, help_text='Users who have contributed to the resource.', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(help_text='Stage explanation.')),
                ('equipment', models.TextField(blank=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResourceCentre.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityStageImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=ResourceCentre.models.uuid4_filename)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('activity_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResourceCentre.ActivityStage')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceSlug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text='Custom resource URL.', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('beavers', models.BooleanField(default=False)),
                ('cubs', models.BooleanField(default=False)),
                ('scouts', models.BooleanField(default=True)),
                ('explorers', models.BooleanField(default=False)),
                ('network', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('curated', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False, help_text='Finished resource.')),
                ('contributors', models.ManyToManyField(blank=True, help_text='Users who have contributed to the resource.', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskAssessmentRisk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk', models.CharField(help_text='State the risk.', max_length=128)),
                ('cause', models.CharField(help_text='State the cause.', max_length=256)),
                ('affectee', models.CharField(choices=[('LE', 'Leaders'), ('YP', 'Young people'), ('EV', 'Everyone')], default='EV', help_text='Who is at risk.', max_length=2)),
                ('severity', models.CharField(choices=[('NE', 'Negligible'), ('LO', 'Low'), ('ME', 'Medium'), ('HI', 'High')], default='ME', help_text='The severity of the risk.', max_length=2)),
                ('chance', models.CharField(choices=[('NE', 'Negligible'), ('LO', 'Low'), ('ME', 'Medium'), ('HI', 'High')], default='LO', help_text='The chance of happening.', max_length=2)),
                ('mitigation', models.CharField(help_text='How will you reduce the risk?', max_length=256)),
                ('responce', models.CharField(help_text='How to respond to an incident.', max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='risks',
            field=models.ManyToManyField(to='ResourceCentre.RiskAssessmentRisk'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='slug',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ResourceCentre.ResourceSlug'),
        ),
        migrations.AddField(
            model_name='activitystage',
            name='risks',
            field=models.ManyToManyField(to='ResourceCentre.RiskAssessmentRisk'),
        ),
        migrations.AddField(
            model_name='activity',
            name='slug',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ResourceCentre.ResourceSlug'),
        ),
    ]
