# Generated by Django 2.0.3 on 2018-04-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceCentre', '0002_auto_20180402_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='slug',
        ),
    ]
