# Generated by Django 2.0 on 2018-01-12 22:11

import ResourceCentre.models.base
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceCentre', '0002_auto_20171222_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='slug',
            field=models.SlugField(default='unfilled', help_text='Keep it short but specific.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camp',
            name='slug',
            field=models.SlugField(default='unfilled', help_text='Keep it short but specific.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='slug',
            field=models.SlugField(default='unfilled', help_text='Keep it short but specific.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='slug',
            field=models.SlugField(default='unfilled', help_text='Keep it short but specific.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskassessmentelement',
            name='slug',
            field=models.SlugField(default='unfilled', help_text='Keep it short but specific.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='beavers',
            field=models.BooleanField(default=False, help_text='Aimed at the Beaver section.'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='cubs',
            field=models.BooleanField(default=False, help_text='Aimed at the Cub section.'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='curated',
            field=models.BooleanField(default=False, help_text='Curated resource.'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='explorers',
            field=models.BooleanField(default=False, help_text='Aimed at the Explorer section.'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='network',
            field=models.BooleanField(default=False, help_text='Aimed at the Beavers section.'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='For if the resource was a copy and edited, the parent.', null=True, on_delete=models.SET(ResourceCentre.models.base.get_sentinel_parent), related_name='activity_children', related_query_name='activity_child', to='ResourceCentre.Activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='risk_assessment',
            field=models.ForeignKey(blank=True, help_text='Event risk assessment.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_events', related_query_name='activity_event', to='ResourceCentre.RiskAssessment'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='scouts',
            field=models.BooleanField(default=True, help_text='Aimed at the Scout section.'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='young_people_approx',
            field=models.BooleanField(default=True, help_text='Is the number of young people an approximate number?'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='beavers',
            field=models.BooleanField(default=False, help_text='Aimed at the Beaver section.'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='cubs',
            field=models.BooleanField(default=False, help_text='Aimed at the Cub section.'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='curated',
            field=models.BooleanField(default=False, help_text='Curated resource.'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='explorers',
            field=models.BooleanField(default=False, help_text='Aimed at the Explorer section.'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='network',
            field=models.BooleanField(default=False, help_text='Aimed at the Beavers section.'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='For if the resource was a copy and edited, the parent.', null=True, on_delete=models.SET(ResourceCentre.models.base.get_sentinel_parent), related_name='camp_children', related_query_name='camp_child', to='ResourceCentre.Camp'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='risk_assessment',
            field=models.ForeignKey(blank=True, help_text='Event risk assessment.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='camp_events', related_query_name='camp_event', to='ResourceCentre.RiskAssessment'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='scouts',
            field=models.BooleanField(default=True, help_text='Aimed at the Scout section.'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='young_people_approx',
            field=models.BooleanField(default=True, help_text='Is the number of young people an approximate number?'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='beavers',
            field=models.BooleanField(default=False, help_text='Aimed at the Beaver section.'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='cubs',
            field=models.BooleanField(default=False, help_text='Aimed at the Cub section.'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='curated',
            field=models.BooleanField(default=False, help_text='Curated resource.'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='explorers',
            field=models.BooleanField(default=False, help_text='Aimed at the Explorer section.'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='network',
            field=models.BooleanField(default=False, help_text='Aimed at the Beavers section.'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='For if the resource was a copy and edited, the parent.', null=True, on_delete=models.SET(ResourceCentre.models.base.get_sentinel_parent), related_name='meeting_children', related_query_name='meeting_child', to='ResourceCentre.Meeting'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='risk_assessment',
            field=models.ForeignKey(blank=True, help_text='Event risk assessment.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meeting_events', related_query_name='meeting_event', to='ResourceCentre.RiskAssessment'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='scouts',
            field=models.BooleanField(default=True, help_text='Aimed at the Scout section.'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='young_people_approx',
            field=models.BooleanField(default=True, help_text='Is the number of young people an approximate number?'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='beavers',
            field=models.BooleanField(default=False, help_text='Aimed at the Beaver section.'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='cubs',
            field=models.BooleanField(default=False, help_text='Aimed at the Cub section.'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='curated',
            field=models.BooleanField(default=False, help_text='Curated resource.'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='explorers',
            field=models.BooleanField(default=False, help_text='Aimed at the Explorer section.'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='network',
            field=models.BooleanField(default=False, help_text='Aimed at the Beavers section.'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='For if the resource was a copy and edited, the parent.', null=True, on_delete=models.SET(ResourceCentre.models.base.get_sentinel_parent), related_name='riskassessment_children', related_query_name='riskassessment_child', to='ResourceCentre.RiskAssessment'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='scouts',
            field=models.BooleanField(default=True, help_text='Aimed at the Scout section.'),
        ),
        migrations.AlterField(
            model_name='riskassessmentelement',
            name='beavers',
            field=models.BooleanField(default=False, help_text='Aimed at the Beaver section.'),
        ),
        migrations.AlterField(
            model_name='riskassessmentelement',
            name='cubs',
            field=models.BooleanField(default=False, help_text='Aimed at the Cub section.'),
        ),
        migrations.AlterField(
            model_name='riskassessmentelement',
            name='curated',
            field=models.BooleanField(default=False, help_text='Curated resource.'),
        ),
        migrations.AlterField(
            model_name='riskassessmentelement',
            name='explorers',
            field=models.BooleanField(default=False, help_text='Aimed at the Explorer section.'),
        ),
        migrations.AlterField(
            model_name='riskassessmentelement',
            name='network',
            field=models.BooleanField(default=False, help_text='Aimed at the Beavers section.'),
        ),
        migrations.AlterField(
            model_name='riskassessmentelement',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='For if the resource was a copy and edited, the parent.', null=True, on_delete=models.SET(ResourceCentre.models.base.get_sentinel_parent), related_name='riskassessmentelement_children', related_query_name='riskassessmentelement_child', to='ResourceCentre.RiskAssessmentElement'),
        ),
        migrations.AlterField(
            model_name='riskassessmentelement',
            name='scouts',
            field=models.BooleanField(default=True, help_text='Aimed at the Scout section.'),
        ),
    ]
