# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BadgeInfo', '0003_auto_20171128_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='stage',
            field=models.IntegerField(blank=True, help_text='Stage, only for staged badges.', null=True),
        ),
    ]
