# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BadgeInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='beavers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='badge',
            name='cubs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='badge',
            name='explorers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='badge',
            name='network',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='badge',
            name='scouts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='title',
            field=models.CharField(default='Empty', help_text='Title, not html.', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='badge',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Date-time updated.'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
