# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BadgeInfo', '0002_auto_20171128_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='stage',
            field=models.IntegerField(blank=True, help_text='Stage, only for staged badges.'),
        ),
    ]
