# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 22:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceCentre', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='time_length',
        ),
        migrations.AddField(
            model_name='activity',
            name='time',
            field=models.DurationField(default='1:0:0', help_text='Activity length.'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='contributors',
            field=models.ManyToManyField(blank=True, help_text='Users who have contributed to the resource.', related_name='activity_contributions', related_query_name='activity_contribution', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='cost_per_young_person',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost per young person.', max_digits=11),
        ),
        migrations.AlterField(
            model_name='activity',
            name='desciption',
            field=models.CharField(blank=True, help_text='Summerise  your resources.', max_length=512),
        ),
        migrations.AlterField(
            model_name='activity',
            name='editors',
            field=models.ManyToManyField(blank=True, help_text='Users with permission to edit the resource.', related_name='activity_editor_roles', related_query_name='activity_editor_role', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='equipment',
            field=models.TextField(blank=True, help_text='Equipment needed to run the event.'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='inside_outside',
            field=models.CharField(choices=[('OU', 'Outside only'), ('IN', 'Inside only'), ('EI', 'Inside or outside'), ('BO', 'Inside and outside')], default='OU', help_text='Is the event inside, outside or both.', max_length=2),
        ),
        migrations.AlterField(
            model_name='activity',
            name='leaders',
            field=models.IntegerField(default=3, help_text='Number of leaders needed.'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='resources',
            field=models.TextField(blank=True, help_text='Resources needed to run the event.'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='risk_assessment',
            field=models.ForeignKey(blank=True, help_text='Event risk assessment.', on_delete=django.db.models.deletion.PROTECT, related_name='activity_events', related_query_name='activity_event', to='ResourceCentre.RiskAssessment'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='young_leaders',
            field=models.IntegerField(default=0, help_text='Number of young leaders.'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='contributors',
            field=models.ManyToManyField(blank=True, help_text='Users who have contributed to the resource.', related_name='camp_contributions', related_query_name='camp_contribution', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='camp',
            name='desciption',
            field=models.CharField(blank=True, help_text='Summerise  your resources.', max_length=512),
        ),
        migrations.AlterField(
            model_name='camp',
            name='editors',
            field=models.ManyToManyField(blank=True, help_text='Users with permission to edit the resource.', related_name='camp_editor_roles', related_query_name='camp_editor_role', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='camp',
            name='equipment',
            field=models.TextField(blank=True, help_text='Equipment needed to run the event.'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='inside_outside',
            field=models.CharField(choices=[('OU', 'Outside only'), ('IN', 'Inside only'), ('EI', 'Inside or outside'), ('BO', 'Inside and outside')], default='OU', help_text='Is the event inside, outside or both.', max_length=2),
        ),
        migrations.AlterField(
            model_name='camp',
            name='leaders',
            field=models.IntegerField(default=3, help_text='Number of leaders needed.'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='resources',
            field=models.TextField(blank=True, help_text='Resources needed to run the event.'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='risk_assessment',
            field=models.ForeignKey(blank=True, help_text='Event risk assessment.', on_delete=django.db.models.deletion.PROTECT, related_name='camp_events', related_query_name='camp_event', to='ResourceCentre.RiskAssessment'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='young_leaders',
            field=models.IntegerField(default=0, help_text='Number of young leaders.'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='contributors',
            field=models.ManyToManyField(blank=True, help_text='Users who have contributed to the resource.', related_name='meeting_contributions', related_query_name='meeting_contribution', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='desciption',
            field=models.CharField(blank=True, help_text='Summerise  your resources.', max_length=512),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='editors',
            field=models.ManyToManyField(blank=True, help_text='Users with permission to edit the resource.', related_name='meeting_editor_roles', related_query_name='meeting_editor_role', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='equipment',
            field=models.TextField(blank=True, help_text='Equipment needed to run the event.'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='inside_outside',
            field=models.CharField(choices=[('OU', 'Outside only'), ('IN', 'Inside only'), ('EI', 'Inside or outside'), ('BO', 'Inside and outside')], default='OU', help_text='Is the event inside, outside or both.', max_length=2),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='leaders',
            field=models.IntegerField(default=3, help_text='Number of leaders needed.'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='resources',
            field=models.TextField(blank=True, help_text='Resources needed to run the event.'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='risk_assessment',
            field=models.ForeignKey(blank=True, help_text='Event risk assessment.', on_delete=django.db.models.deletion.PROTECT, related_name='meeting_events', related_query_name='meeting_event', to='ResourceCentre.RiskAssessment'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='young_leaders',
            field=models.IntegerField(default=0, help_text='Number of young leaders.'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='contributors',
            field=models.ManyToManyField(blank=True, help_text='Users who have contributed to the resource.', related_name='riskassessment_contributions', related_query_name='riskassessment_contribution', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='desciption',
            field=models.CharField(blank=True, help_text='Summerise  your resources.', max_length=512),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='editors',
            field=models.ManyToManyField(blank=True, help_text='Users with permission to edit the resource.', related_name='riskassessment_editor_roles', related_query_name='riskassessment_editor_role', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='riskassessmentelement',
            name='contributors',
            field=models.ManyToManyField(blank=True, help_text='Users who have contributed to the resource.', related_name='riskassessmentelement_contributions', related_query_name='riskassessmentelement_contribution', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='riskassessmentelement',
            name='desciption',
            field=models.CharField(blank=True, help_text='Summerise  your resources.', max_length=512),
        ),
        migrations.AlterField(
            model_name='riskassessmentelement',
            name='editors',
            field=models.ManyToManyField(blank=True, help_text='Users with permission to edit the resource.', related_name='riskassessmentelement_editor_roles', related_query_name='riskassessmentelement_editor_role', to=settings.AUTH_USER_MODEL),
        ),
    ]
