# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceCentre', '0004_auto_20171127_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='time',
        ),
        migrations.AddField(
            model_name='activity',
            name='time_length',
            field=models.DurationField(default=django.utils.timezone.now, help_text='Activity length.'),
            preserve_default=False,
        ),
    ]
