# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceCentre', '0006_auto_20171127_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.DurationField(default=1200, help_text='Activity length.'),
        ),
    ]
