# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceCentre', '0009_auto_20171127_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.DurationField(default=3600.0, help_text='Activity length.'),
        ),
    ]
